id: A68580FD4
base_file: f11C9.txt
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-05-30 20:42:06.952876
  last_modified_at: 2022-05-30 20:42:06.952885
